=== yonue/mini-projet-cl-en-main-sur-les-Donn-es-Semi-Structur-es-DSS-/miniprojet2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Les elements declares ici sont globaux -->

    <!-- Declarations globales des elements de type simple (les feuilles de l'arbre) -->

    <xs:element name="nom" type="xs:string"/>
    <xs:element name="type" type="xs:string"/>
    <!-- <xs:element name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="animal"/>
                <xs:enumeration value="plante"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element> -->
    <xs:element name="description" type="xs:string"/>
    <xs:element name="pays" type="xs:string"/>
    <xs:element name="nb_individu" type="xs:nonNegativeInteger"/>
    <xs:element name="annee" type="xs:nonNegativeInteger"/>

    <!-- Types complexes  -->
    
    <xs:complexType name="MiniProjetType">
        <!-- Le document contient un ensemble d'especes -->
        <xs:sequence>
            <xs:element ref="especes"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EspecesType">
        <!-- Au moins une espece est attendue -->
        <xs:sequence>
            <xs:element ref="espece" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EspeceType">
        <!-- Une espece possede ses informations generales(type, nom, description) et ses lieux d'observation -->
        <xs:sequence>
            <xs:element ref="type"/>
            <xs:element ref="nom"/>
            <xs:element ref="description"/>
            <xs:element ref="les_lieux"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="LieuxType">
        <!-- Une espece peut être observee dans un ou plusieurs lieux -->
        <xs:sequence>
            <xs:element ref="lieu" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LieuType">
        <!-- Chaque lieu possede un identifiant, un nom, un pays et des observations -->
        <xs:sequence>
            <xs:element ref="nom"/>
            <xs:element ref="pays"/>
            <xs:element ref="observations"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="ObservationsType">
        <!-- Un lieu contient au moins une observation -->
        <xs:sequence>
            <xs:element ref="observation" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ObservationType">
        <!-- Une observation associe une annee à un nombre d'individus -->
        <xs:sequence>
            <xs:element ref="annee"/>
            <xs:element ref="nb_individu"/>
        </xs:sequence>
    </xs:complexType>
    

  <!-- la definition des elements de type complexe -->

    <xs:element name="mini_projet" type="MiniProjetType"/>
    <xs:element name="especes" type="EspecesType"/>
    <xs:element name="espece" type="EspeceType"/>

    <xs:element name="les_lieux" type="LieuxType"/>
    <xs:element name="lieu" type="LieuType"/>

    <xs:element name="observations" type="ObservationsType"/>
    <xs:element name="observation" type="ObservationType"/>

</xs:schema>

=== yonue/mini-projet-cl-en-main-sur-les-Donn-es-Semi-Structur-es-DSS-/miniprojet2.xml
<?xml version="1.0" encoding="UTF-8"?>


<!-- Document XML organise par espece, puis par lieu et par observation -->
<mini_projet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="miniprojet2.xsd">

    <!-- Ensemble des especes -->
    <especes>
        <!-- Une espece possede un identifiant, un type, un nom, une description et des lieux -->
        <espece id="E01">
            <type> plante </type>
            <nom> Paphiopedilum villeux </nom>
            <description> Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides. 
            </description>

            <!--Les lieux où les espèces ont ete observee -->
            <!-- Les lieux possedent id, nom, pays et des observations-->
            <les_lieux>
                <lieu id="L01">
                    <nom> Chiang Mai </nom>
                    <pays> Thaïlande </pays>

                    <!-- nb_individu observes au cours des differentes annees -->
                    <observations>

                        <!-- Chaque observation contient aneee et nb_individu -->
                        <observation>
                            <annee> 2021 </annee>
                            <nb_individu> 48 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2022 </annee>
                            <nb_individu> 44 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2023 </annee>
                            <nb_individu>39  </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2024 </annee>
                            <nb_individu> 35 </nb_individu>
                        </observation>
                    </observations>
                </lieu>
                <lieu id="L02">
                    <nom> Doi Inthanon </nom>
                    <pays> Thaïlande </pays>
                    <observations>
                        <observation>
                            <annee> 2021 </annee>
                            <nb_individu> 42 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2022 </annee>
                            <nb_individu> 38 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2023 </annee>
                            <nb_individu>34  </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2024 </annee>
                            <nb_individu> 30 </nb_individu>
                        </observation>
                    </observations>
                </lieu>
            </les_lieux>
        </espece>

        <espece id="E02">
            <type> animal </type>
            <nom> elephant d'Afrique </nom>
            <description> Grand mammifère herbivore vivant principalement 
                dans les savanes et les forêts africaines.</description>
            <les_lieux>
                <lieu id="L03">
                    <nom> Parc national de Niokolo-Koba </nom>
                    <pays> Senegal </pays>
                    <observations>
                        <observation>
                            <annee> 2022 </annee>
                            <nb_individu> 120 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2023 </annee>
                            <nb_individu> 114 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2024 </annee>
                            <nb_individu>108  </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2025 </annee>
                            <nb_individu> 120 </nb_individu>
                        </observation>
                    </observations>
                </lieu>
                <lieu id="L04">
                    <nom> zakouma </nom>
                    <pays> tchad </pays>
                    <observations>
                        <observation>
                            <annee> 2022 </annee>
                            <nb_individu> 98 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2023 </annee>
                            <nb_individu> 90 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2024 </annee>
                            <nb_individu>83  </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2025 </annee>
                            <nb_individu> 75 </nb_individu>
                        </observation>
                    </observations>
                </lieu>
            </les_lieux>
        </espece>


        <espece id="E03">
            <type> animal </type>
            <nom> Gorille des plaines de l'Ouest </nom>
            <description> Grand primate vivant principalement dans 
                les forêts tropicales d'Afrique centrale. </description>
            <les_lieux>
                <lieu id="L05">
                    <nom> Parc national d'Odzala-Kokoua </nom>
                    <pays> RDC </pays>
                    <observations>
                        <observation>
                            <annee> 2022 </annee>
                            <nb_individu> 80 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2023 </annee>
                            <nb_individu> 76 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2024 </annee>
                            <nb_individu>71  </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2025 </annee>
                            <nb_individu> 68 </nb_individu>
                        </observation>
                    </observations>
                </lieu>
                <lieu id="L06">
                    <nom> Loango </nom>
                    <pays> TCHAD </pays>
                    <observations>
                        <observation>
                            <annee> 2022 </annee>
                            <nb_individu> 65 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2023 </annee>
                            <nb_individu> 62 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2024 </annee>
                            <nb_individu>59  </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2025 </annee>
                            <nb_individu> 56 </nb_individu>
                        </observation>
                    </observations>
                </lieu>
            </les_lieux>
        </espece>

        <espece id="E04">
            <type> plante </type>
            <nom> Staurogyne bicolor </nom>
            <description> Staurogyne bicolor est une plante herbacee de la famille des
                       Acanthaceae, endemique du Cameroun. Elle se developpe principalement
                       dans des environnements tropicaux humides et forestiers. L'espèce est
                       classee Vulnerable (VU) sur la Liste rouge de l'UICN.
            </description>
            <les_lieux>
                <lieu id="L07">
                    <nom> Mont Koupe </nom>
                    <pays> cameroun </pays>
                    <observations>
                        <observation>
                            <annee> 2021 </annee>
                            <nb_individu> 62 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2022 </annee>
                            <nb_individu> 58 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2023 </annee>
                            <nb_individu>57  </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2024 </annee>
                            <nb_individu> 51 </nb_individu>
                        </observation>
                    </observations>
                </lieu>
                <lieu id="L08">
                    <nom> Monts Bakossi </nom>
                    <pays> cameroun </pays>
                    <observations>
                        <observation>
                            <annee> 2021 </annee>
                            <nb_individu> 57 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2022 </annee>
                            <nb_individu> 53 </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2023 </annee>
                            <nb_individu>49  </nb_individu>
                        </observation>
                        <observation>
                            <annee> 2024 </annee>
                            <nb_individu> 46 </nb_individu>
                        </observation>
