=== yonue/mini-projet-cl-en-main-sur-les-Donn-es-Semi-Structur-es-DSS-/miniprojet.dtd
<!-- element racine c'est mini_projet, qui contient des sous elements OBSERVATIONS -->
<!ELEMENT mini_projet (observations)>

<!-- La liste doit contenir au moins une observation -->
<!ELEMENT observations (observation+)>

<!-- Une observation regroupe une espece, un lieu, une annee et un nb_individu -->
<!ELEMENT observation (espece, lieu, annee, nb_individu)>

<!-- Description de l'espece observee -->
<!ELEMENT espece (type, nom, description)>

<!-- L'identifiant de l'espece est obligatoire -->
<!ATTLIST espece id CDATA #REQUIRED>

<!ELEMENT type (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!-- Identification du lieu où l'espece a ete observee -->
<!ELEMENT lieu (nom, pays)>

<!-- ID du lieu est obligatoire et doit être unique -->
<!ATTLIST lieu id ID #REQUIRED>
<!ELEMENT pays (#PCDATA)>

<!-- Annee de l'observation et nombre d'individus recenses -->
<!ELEMENT annee (#PCDATA)>
<!ELEMENT nb_individu (#PCDATA)>

=== yonue/mini-projet-cl-en-main-sur-les-Donn-es-Semi-Structur-es-DSS-/miniprojet1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mini_projet SYSTEM "miniprojet.dtd">

<!-- 2 especes(animal, plante), pour chaque especes 
    on a deux lieux, et par chaque lieux il y a 4 observations-->


<!-- Element observations contient des sous elements OBSERVATION -->


<!-- Element Observation contient sous element ESPECE, LIEU, ANNEE et NB_INDIVIDU-->


<!-- Chaque element ESPECE contient (type, nom, description) -->


<!-- Chaque element Lieu contient (nom, pays) -->


<mini_projet>

    <observations>

        <observation>
            <espece id="E01"> 
                <type>plante</type>
                <nom>Paphiopedilum villosum</nom>
                <description>
                    Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides.
                </description>
            </espece>

            <lieu id="L01">
                <nom>Chiang Mai</nom>
                <pays>Thaïlande</pays>
            </lieu>

            <annee>2021</annee>
            <nb_individu>48</nb_individu>
        </observation>

        <observation>
            <espece id="E01">
                <type>plante</type>
                <nom>Paphiopedilum villosum</nom>
                <description>
                    Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides.
                </description>
            </espece>

            <lieu id="L01">
                <nom>Chiang Mai</nom>
                <pays>Thaïlande</pays>
            </lieu>

            <annee>2022</annee>
            <nb_individu>44</nb_individu>
        </observation>

        <observation>
            <espece id="E01">
                <type>plante</type>
                <nom>Paphiopedilum villosum</nom>
                <description>
                    Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides.
                </description>
            </espece>

            <lieu id="L01">
                <nom>Chiang Mai</nom>
                <pays>Thaïlande</pays>
            </lieu>

            <annee>2023</annee>
            <nb_individu>39</nb_individu>
        </observation>

        <observation>
            <espece id="E01">
                <type>plante</type>
                <nom>Paphiopedilum villosum</nom>
                <description>
                    Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides.
                </description>
            </espece>

            <lieu id="L01">
                <nom>Chiang Mai</nom>
                <pays>Thaïlande</pays>
            </lieu>

            <annee>2024</annee>
            <nb_individu>35</nb_individu>
        </observation>


        <observation>
            <espece id="E01">
                <type>plante</type>
                <nom>Paphiopedilum villosum</nom>
                <description>
                    Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides.
                </description>
            </espece>

            <lieu id="L02">
                <nom>Doi Inthanon</nom>
                <pays>Thaïlande</pays>
            </lieu>

            <annee>2021</annee>
            <nb_individu>42</nb_individu>
        </observation>

        <observation>
            <espece id="E01">
                <type>plante</type>
                <nom>Paphiopedilum villosum</nom>
                <description>
                    Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides.
                </description>
            </espece>

            <lieu id="L02">
                <nom>Doi Inthanon</nom>
                <pays>Thaïlande</pays>
            </lieu>

            <annee>2022</annee>
            <nb_individu>38</nb_individu>
        </observation>

        <observation>
            <espece id="E07">
                <type>plante</type>
                <nom>Paphiopedilum villosum</nom>
                <description>
                    Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides.
                </description>
            </espece>

            <lieu id="L02">
                <nom>Doi Inthanon</nom>
                <pays>Thaïlande</pays>
            </lieu>

            <annee>2023</annee>
            <nb_individu>34</nb_individu>
        </observation>

        <observation>
            <espece id="E01">
                <type>plante</type>
                <nom>Paphiopedilum villosum</nom>
                <description>
                    Paphiopedilum villosum est une orchidée tropicale
                    de la famille des Orchidaceae. Elle peut pousser
                    comme épiphyte ou lithophyte dans des environnements
                    tropicaux humides.
                </description>
            </espece>

            <lieu id="L02">
                <nom>Doi Inthanon</nom>
                <pays>Thaïlande</pays>
            </lieu>

            <annee>2024</annee>
            <nb_individu>30</nb_individu>
        </observation>



        <observation>
            <espece id="E02">
                <type>animal</type>
                <nom>Éléphant d'Afrique</nom>
                <description>
                    Grand mammifère herbivore vivant principalement
                    dans les savanes et les forêts africaines.
                </description>
            </espece>

            <lieu id="L03">
                <nom>Parc national de Niokolo-Koba</nom>
                <pays>Sénégal</pays>
            </lieu>

            <annee>2022</annee>
            <nb_individu>120</nb_individu>
        </observation>

        <observation>
            <espece id="E02">
                <type>animal</type>
                <nom>Éléphant d'Afrique</nom>
                <description>
                    Grand mammifère herbivore vivant principalement
                    dans les savanes et les forêts africaines.
                </description>
            </espece>

            <lieu id="L03">
                <nom>Parc national de Niokolo-Koba</nom>
                <pays>Sénégal</pays>
            </lieu>

            <annee>2023</annee>
            <nb_individu>114</nb_individu>
        </observation>

        <observation>
            <espece id="E02">
                <type>animal</type>
                <nom>Éléphant d'Afrique</nom>
                <description>
                    Grand mammifère herbivore vivant principalement
                    dans les savanes et les forêts africaines.
                </description>
            </espece>

            <lieu id="L03">
                <nom>Parc national de Niokolo-Koba</nom>
                <pays>Sénégal</pays>
            </lieu>

            <annee>2024</annee>
            <nb_individu>108</nb_individu>
        </observation>

        <observation>
            <espece id="E02">
                <type>animal</type>
                <nom>Éléphant d'Afrique</nom>
                <description>
                    Grand mammifère herbivore vivant principalement
                    dans les savanes et les forêts africaines.
                </description>
            </espece>

            <lieu id="L03">
                <nom>Parc national de Niokolo-Koba</nom>
                <pays>Sénégal</pays>
            </lieu>

            <annee>2025</annee>
            <nb_individu>120</nb_individu>
        </observation>



        <observation>
            <espece id="E02">
                <type>animal</type>
                <nom>Éléphant d'Afrique</nom>
                <description>
                    Grand mammifère herbivore vivant principalement
                    dans les savanes et les forêts africaines.
                </description>
            </espece>

            <lieu id="L04">
                <nom>Zakouma</nom>
                <pays>Tchad</pays>
            </lieu>

            <annee>2022</annee>
            <nb_individu>98</nb_individu>
        </observation>

        <observation>
            <espece id="E02">
                <type>animal</type>
                <nom>Éléphant d'Afrique</nom>
                <description>
                    Grand mammifère herbivore vivant principalement
                    dans les savanes et les forêts africaines.
                </description>
            </espece>

            <lieu id="L04">
                <nom>Zakouma</nom>
                <pays>Tchad</pays>
            </lieu>

            <annee>2023</annee>
            <nb_individu>90</nb_individu>
        </observation>

        <observation>
            <espece id="E02">
                <type>animal</type>
                <nom>Éléphant d'Afrique</nom>
                <description>
                    Grand mammifère herbivore vivant principalement
                    dans les savanes et les forêts africaines.
                </description>
            </espece>

            <lieu id="L04">
